### ISSUE TITLE
DEICODE toy tutorial not working in qiime2-amplicon-2024.5 version

### ISSUE THREAD

**Issue by magibc** [cjm007/DEICODE#68]
Hi @cameronmartino and @mortonjt  and other developers of DEICODE plugin,

For reviewers requirements, I need to compute DEICODE and Gemelli in different otu_table (outside QIIME2, as standalone).

As first attempt I tried to replicate the toy tutorial as standalone tool (https://nbviewer.org/github/biocore/DEICODE/blob/master/ipynb/tutorials/moving-pictures-standalone-cli-and-api.ipynb) and also as qiime2  (https://library.qiime2.org/plugins/deicode/19/). 

Nevertheless, both tutorials does not work at least on qiime2-amplicon-2024.5 version.

I attach below the error obtained related to NumPy and also the log if it can helps you:

Tutorial followed:  https://library.qiime2.org/plugins/deicode/19/

```
(qiime2-amplicon-2024.5) dbarscortina@n22:/work_home/dbarscortina/Deicode/as_qiime$ ls
sample-metadata.tsv  table.qza  taxonomy.qza
(qiime2-amplicon-2024.5) dbarscortina@n22:/work_home/dbarscortina/Deicode/as_qiime$ qiime deicode rpca \
>     --i-table table.qza \
>     --p-min-feature-count 10 \
>     --p-min-sample-count 500 \
>     --o-biplot ordination.qza \
>     --o-distance-matrix distance.qza
Plugin error from deicode:

  module 'numpy' has no attribute 'int'.
  `np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
  The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
      https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

Debug info has been saved to /tmp/qiime2-q2cli-err-l5bsd1qx.log
```

How can I fix this issue? 

Thanks on advance for your comments and help,

Maggie.
[qiime2-q2cli-err-l5bsd1qx.log](https://github.com/user-attachments/files/17234391/qiime2-q2cli-err-l5bsd1qx.log)
